/*
* generated by Xtext
*/
package com.br.refactoring.xtext.ui.contentassist;

import com.br.refactoring.xtext.ui.contentassist.AbstractDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DslProposalProvider extends AbstractDslProposalProvider {

}
