/*
* generated by Xtext
*/
package com.br.refactoring.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.br.refactoring.xtext.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {
	
	@Inject
	private DslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser createParser() {
		com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser result = new com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getElementTypeAccess().getAlternatives(), "rule__ElementType__Alternatives");
					put(grammarAccess.getBasicTypeAccess().getTypeNameAlternatives_0(), "rule__BasicType__TypeNameAlternatives_0");
					put(grammarAccess.getRefactoringAccess().getAlternatives(), "rule__Refactoring__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getRenameFeatureAccess().getGroup(), "rule__RenameFeature__Group__0");
					put(grammarAccess.getRenameClassAccess().getGroup(), "rule__RenameClass__Group__0");
					put(grammarAccess.getRenameAttributeAccess().getGroup(), "rule__RenameAttribute__Group__0");
					put(grammarAccess.getRenameMethodAccess().getGroup(), "rule__RenameMethod__Group__0");
					put(grammarAccess.getMovingFeaturesBetweenObjectsAccess().getGroup(), "rule__MovingFeaturesBetweenObjects__Group__0");
					put(grammarAccess.getMoveAttributeAccess().getGroup(), "rule__MoveAttribute__Group__0");
					put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
					put(grammarAccess.getModelAccess().getImportsAssignment_2(), "rule__Model__ImportsAssignment_2");
					put(grammarAccess.getModelAccess().getContainsAssignment_3(), "rule__Model__ContainsAssignment_3");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getClassAccess().getNameAssignment_1(), "rule__Class__NameAssignment_1");
					put(grammarAccess.getClassAccess().getAttributesAssignment_3(), "rule__Class__AttributesAssignment_3");
					put(grammarAccess.getClassAccess().getMethodsAssignment_4(), "rule__Class__MethodsAssignment_4");
					put(grammarAccess.getAttributeAccess().getElementTypeAssignment_1(), "rule__Attribute__ElementTypeAssignment_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_2(), "rule__Attribute__NameAssignment_2");
					put(grammarAccess.getBasicTypeAccess().getTypeNameAssignment(), "rule__BasicType__TypeNameAssignment");
					put(grammarAccess.getClassTypeAccess().getClassTypeAssignment(), "rule__ClassType__ClassTypeAssignment");
					put(grammarAccess.getMethodAccess().getNameAssignment_1(), "rule__Method__NameAssignment_1");
					put(grammarAccess.getRenameFeatureAccess().getNameAssignment_1(), "rule__RenameFeature__NameAssignment_1");
					put(grammarAccess.getRenameFeatureAccess().getAllRefactoringsAssignment_3(), "rule__RenameFeature__AllRefactoringsAssignment_3");
					put(grammarAccess.getRenameFeatureAccess().getAllRefactoringsAssignment_4(), "rule__RenameFeature__AllRefactoringsAssignment_4");
					put(grammarAccess.getRenameFeatureAccess().getAllRefactoringsAssignment_5(), "rule__RenameFeature__AllRefactoringsAssignment_5");
					put(grammarAccess.getRenameClassAccess().getNameAssignment_1(), "rule__RenameClass__NameAssignment_1");
					put(grammarAccess.getRenameClassAccess().getClassToBeRenameAssignment_5(), "rule__RenameClass__ClassToBeRenameAssignment_5");
					put(grammarAccess.getRenameClassAccess().getNewNameAssignment_8(), "rule__RenameClass__NewNameAssignment_8");
					put(grammarAccess.getRenameAttributeAccess().getNameAssignment_1(), "rule__RenameAttribute__NameAssignment_1");
					put(grammarAccess.getRenameAttributeAccess().getSourceClassAssignment_5(), "rule__RenameAttribute__SourceClassAssignment_5");
					put(grammarAccess.getRenameAttributeAccess().getAttributeToBeRenameAssignment_8(), "rule__RenameAttribute__AttributeToBeRenameAssignment_8");
					put(grammarAccess.getRenameAttributeAccess().getNewNameAssignment_11(), "rule__RenameAttribute__NewNameAssignment_11");
					put(grammarAccess.getRenameMethodAccess().getNameAssignment_1(), "rule__RenameMethod__NameAssignment_1");
					put(grammarAccess.getRenameMethodAccess().getSourceClassAssignment_5(), "rule__RenameMethod__SourceClassAssignment_5");
					put(grammarAccess.getRenameMethodAccess().getMethodToBeRenameAssignment_8(), "rule__RenameMethod__MethodToBeRenameAssignment_8");
					put(grammarAccess.getRenameMethodAccess().getNewNameAssignment_11(), "rule__RenameMethod__NewNameAssignment_11");
					put(grammarAccess.getMovingFeaturesBetweenObjectsAccess().getNameAssignment_1(), "rule__MovingFeaturesBetweenObjects__NameAssignment_1");
					put(grammarAccess.getMovingFeaturesBetweenObjectsAccess().getAllRefactoringsAssignment_3(), "rule__MovingFeaturesBetweenObjects__AllRefactoringsAssignment_3");
					put(grammarAccess.getMoveAttributeAccess().getNameAssignment_1(), "rule__MoveAttribute__NameAssignment_1");
					put(grammarAccess.getMoveAttributeAccess().getSourceClassAssignment_5(), "rule__MoveAttribute__SourceClassAssignment_5");
					put(grammarAccess.getMoveAttributeAccess().getTargetClassAssignment_8(), "rule__MoveAttribute__TargetClassAssignment_8");
					put(grammarAccess.getMoveAttributeAccess().getAttributeToBeMovedAssignment_11(), "rule__MoveAttribute__AttributeToBeMovedAssignment_11");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser typedParser = (com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
