/*
* generated by Xtext
*/
package com.br.refactoring.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.br.refactoring.xtext.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {
	
	@Inject
	private DslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser createParser() {
		com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser result = new com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getRenameFeatureAccess().getGroup(), "rule__RenameFeature__Group__0");
					put(grammarAccess.getRenameClassAccess().getGroup(), "rule__RenameClass__Group__0");
					put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
					put(grammarAccess.getModelAccess().getImportsAssignment_2(), "rule__Model__ImportsAssignment_2");
					put(grammarAccess.getModelAccess().getContainsAssignment_3(), "rule__Model__ContainsAssignment_3");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getClassAccess().getNameAssignment_1(), "rule__Class__NameAssignment_1");
					put(grammarAccess.getRenameFeatureAccess().getNameAssignment_1(), "rule__RenameFeature__NameAssignment_1");
					put(grammarAccess.getRenameFeatureAccess().getAllRefactoringsAssignment_3(), "rule__RenameFeature__AllRefactoringsAssignment_3");
					put(grammarAccess.getRenameClassAccess().getNameAssignment_1(), "rule__RenameClass__NameAssignment_1");
					put(grammarAccess.getRenameClassAccess().getClassToBeRenameAssignment_5(), "rule__RenameClass__ClassToBeRenameAssignment_5");
					put(grammarAccess.getRenameClassAccess().getNewNameAssignment_8(), "rule__RenameClass__NewNameAssignment_8");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser typedParser = (com.br.refactoring.xtext.ui.contentassist.antlr.internal.InternalDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
